### ISSUE TITLE
Error loading devices with docker compose

### ISSUE THREAD

**Issue by onlymejosh** [nurikk/z2m-frontend#237] opened 2021-01-02 21:24 UTC
hey, I am running into issues getting the frontend for z2m loading with `docker-compose` similar to the issues listed here https://github.com/Koenkk/zigbee2mqtt/issues/4266#issuecomment-752680322

here is my docker compose service:
```
zigbee2mqtt:
    container_name: zigbee2mqtt
    depends_on:
      - mosquitto
    image: koenkk/zigbee2mqtt:1.16.2
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    environment:
      - TZ=Europe/London
    network_mode: host
    ports:
      - 8080:8080
```

I get the error
```Loading devices takes too long time. Consider reading documentation```
When visiting http://10.27.1.114:8080/

I dont see any errors in the logs both console and zigbee2mqtt

**Comment by nmaupu** [comment] 2021-01-02 21:34
I have the exact same problem using a standalone installation on a RPI.
Zigbee2Mqtt version: 1.16.2
Configuration:
```
frontend:
  port: 8080
  host: 0.0.0.0
```

**Comment by nmaupu** [comment] 2021-01-02 21:36
Possible duplicate of #203

**Comment by nmaupu** [comment] 2021-01-02 22:07
Working ok with version 1.17.0 commit: 07cdc9d 👍

**Comment by hackex** [comment] 2021-01-05 09:13
I am getting an error as well using version 1.17.0.1
The device page just doesn't load anymore.

**Comment by florianschroen** [comment] 2021-01-06 21:22
This is not independent to docker compose. Also happening with "plain" `docker run` and normal install without docker.

This ticket seems to be a duplicate for https://github.com/nurikk/z2m-frontend/issues/203

**Comment by bachoo786** [comment] 2021-01-11 13:04
Hi 

is this issue resolved yet? I have facing the same problem as described in the OP.

thanks

**Comment by Morphy99** [comment] 2021-01-11 20:12
> Hi
> 
> is this issue resolved yet? I have facing the same problem as described in the OP.
> 
> thanks

Yep see [here](https://github.com/nurikk/z2m-frontend/issues/203#issuecomment-757502067)

**Comment by florianschroen** [comment] 2021-01-13 21:06
For me it is fixed with today's koenkk/zigbee2mqtt:latest-dev

**Comment by nurikk** [comment] 2021-01-14 09:27
Closing then

**Closed by nurikk** 2021-01-14 09:27 UTC
