### ISSUE TITLE
Error EGLO CONNECT zigbee2mqtt

### ISSUE THREAD

**Issue by MuKo2018** [nurikk/z2m-frontend#2327] opened 2024-12-22 14:34 UTC
### What happened?

TypeError
<head></head>
0xa4c13866a031a304 | 0xa4c13866a031a304(0x56D8) | Nicht unterstützt |   | N/A |  
-- | -- | -- | -- | -- | --

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">[0xa4c13866a031a304](http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/#/device/0xa4c13866a031a304)
0xa4c13866a031a304
(0x56D8)
Nicht unterstützt		N/A
[initialState.json.zip](https://github.com/user-attachments/files/18222154/initialState.json.zip)

### What browsers are you seeing the problem on?

Safari

### Relevant stacktrace

```shell
**Current url**: http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/#/device/0xa4c13866a031a304/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: undefined is not an object (evaluating 'c.endpoints[r].clusters')



render@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/ConnectedDevicePage-904482a0.js:1:31231
ab@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:6192
J5@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:39758
Oze@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:39684
ap@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:39537
cb@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:35902
AD@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:36706
Gn@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:41:3284
@http://10.0.0.152:8123/api/hassio_ingress/kqfCTvVeIsUiT--gH82ldumeHWKi33uSHFgUBR3TqmQ/assets/index-1213f99f.js:43:34232
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-22 19:59
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-22 19:59 UTC
Labels: bug
