### ISSUE TITLE
device settings-specific refresh itself

### ISSUE THREAD

**Issue by timoline** [nurikk/z2m-frontend#489] opened 2021-05-03 04:50 UTC
When pressing the + button it lookslike the page refresh itself after a few seconds, so there is no way to press submit :-)

**Comment by weltmeyer** [comment] 2021-05-04 12:18
Same happens on the reporting settings page.. cant set it as it refreshes and clears my selections before i am able to press "apply"

**Comment by timoline** [comment] 2021-05-05 04:28
Also on bind page...

**Comment by JoachimEngelmann** [comment] 2021-05-10 22:40
I have the same issue. The cause for this if z2m receives some zigbee packages. I can reproduce it with a zigbee button (Hue dimmer switch), open a mentioned menue item, press the button -> menue closes

**Comment by Claude2666** [comment] 2021-05-15 08:37
I have the same problem. Running frontend   0.4.10.  When I try to update Reporting or Settings of a device, the page is automatically refreshed after a few seconds, clearing all fields I entered, making it impossible to update something.

**Comment by JoachimEngelmann** [comment] 2021-05-16 12:45
Same issue in "Bind"

**Comment by nurikk** [comment] 2021-05-17 01:17
Fixed in latest dev branch

**Comment by afoeder** [comment] 2021-05-19 13:12
is this the same as #528?

**Comment by nurikk** [comment] 2021-05-19 13:28
> is this the same as #528?

Yes

**Comment by Claude2666** [comment] 2021-05-21 13:49
I can confirm that with frontend 0.4.15 it is working properly.

Thanks.

**Comment by timoline** [comment] 2021-05-21 14:02
> I can confirm that with frontend 0.4.15 it is working properly.
> 
> Thanks.

How can you tell?
The device-specific page is under construction :-)

**Comment by Claude2666** [comment] 2021-05-21 14:23
I just updated zibee2mqtt to the latest dev and it came with frontend 0.4.15  No the page is no longer refreshed.  I can enter values in the reporting tab without them being erased.

**Closed** 2021-05-21 14:25 UTC

**Comment by smulle48** [comment] 2021-05-28 09:36
The problem is still there on the Bind page
