### ISSUE TITLE
Hue Bloom Will Not Add to ZHA

### ISSUE THREAD

**Issue by kajishun** [nurikk/z2m-frontend#2331] opened 2024-12-23 06:41 UTC
### What happened?

Hue Bloom works fine on Hue Bridge Gen2. Bloom is seen by HA via the Hue integration. When attempting to add Bloom to Z2M, the interview does not complete. Bloom is seen in ZHA at first. Then it becomes unresponsive until unplugged/replugged. Problem repeats in ZHA. Problem is in HA app on iPad.

![IMG_0002](https://github.com/user-attachments/assets/9f195ffb-8cc5-4a6b-a855-93cc773fc33a)

[initialState.json.zip](https://github.com/user-attachments/files/18225989/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/#/device/0x00178801033117ea/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: undefined is not an object (evaluating 'c.endpoints[r].clusters')



render@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/ConnectedDevicePage-904482a0.js:1:31231
ab@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:6192
J5@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:39758
Oze@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:39684
ap@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:39537
cb@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:35902
AD@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:36706
Gn@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:41:3284
@http://192.168.20.222:8123/api/hassio_ingress/NmDHvDh3MtiZoG74maER48sp32fyxaLjss3GzSmbCCY/assets/index-1213f99f.js:43:34232
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-23 19:54
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-23 19:54 UTC
Labels: bug
