### ISSUE TITLE
Fields are emptied automatically 

### ISSUE THREAD

**Issue by rindlerblabla** [nurikk/z2m-frontend#528] opened 2021-05-14 19:06 UTC
Am pretty new to z2m and I am really happy with it. However the fields are emptied automatically if I am not fast enough to submit the changes. And I mean, I have to be really fast. It happens no matter what fields I am typing in, like when I type which attributes to exclude, what clusters to bind. The page is not reloaded, only the fields are emptied. 

Talked to some other users over Discord and obviously they experienced the same, and that this bug is fairly new. Would be nice if it could be solved! Am running z2m in a Synology Docker using 1.18.3-dev, frontend 0.4.2.

**Comment by afoeder** [comment] 2021-05-19 13:10
+1, the issue is very likely related to a DOM redraw/rewrite:

![image](https://user-images.githubusercontent.com/1125168/118816644-abbe5880-b8b2-11eb-84ce-40764686f2d7.png)

the highlighted `div` gets redrawn every couple (5ish?) of seconds, and I even think it correlates with the MQTT updates! 

Here's a screen recording that shows the issue in correlation with what happens on MQTT:

![Screen Recording 2021-05-19 at 3 00 07 PM](https://user-images.githubusercontent.com/1125168/118818174-5125fc00-b8b4-11eb-9920-dae4ffcbc071.gif)

**Comment by nurikk** [comment] 2021-05-19 13:29
Duplicate of #489

**Closed by nurikk** 2021-05-19 13:29 UTC
