### ISSUE TITLE
Text "Hello, you've found a bug. Congratulations!" adding an tongou device. TO-Q-SY2-JZT

### ISSUE THREAD

**Issue by angaro142** [nurikk/z2m-frontend#2300] opened 2024-12-13 22:33 UTC
### What happened?

This error happen when I was trieing to add the device to zigbee2mqtt. This device is not supported. When I go to "dev console" I find this message : "Hello, you've found a bug. Congratulations!"
[initialState.json.zip](https://github.com/user-attachments/files/18132534/initialState.json.zip)
[initialState.json.zip](https://github.com/user-attachments/files/18132546/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/#/device/0xdc8e95fffe8ae2e9/dev-console
**Previous url**: https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:6186)
    at _D (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:5982)
    at a3 (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:44865)
    at J5 (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:39756)
    at Oze (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:39682)
    at ap (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:39534)
    at cb (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:35900)
    at AD (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:43:36704)
    at Gn (https://aq7ilomu0si0cs77gzayk1ej3ywzmlv9.ui.nabu.casa/api/hassio_ingress/RXcyYxe7I5zsO-VxxUHgvGRhGMnFEV1CkYULFAXoxpM/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-14 13:22
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-14 13:22 UTC
Labels: bug
