### ISSUE TITLE
Error connection of IKEA Parasoll (E2013)

### ISSUE THREAD

**Issue by Zimolus** [nurikk/z2m-frontend#2326] opened 2024-12-22 13:29 UTC
### What happened?

I have tried to connect the Parasoll (E2013) from IKEA. This error appears. 

[initialState.json.zip](https://github.com/user-attachments/files/18221978/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/#/device/0xf84477fffedbbff0/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:6186)
    at _D (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:5982)
    at a3 (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:44865)
    at J5 (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:39756)
    at Oze (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:35900)
    at AD (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/C36_c_SCdaC-8Uv-0X9BkThb8KNUWgqMjF-vM78B8oE/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-22 20:00
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-22 20:00 UTC
Labels: bug
