### ISSUE TITLE
Zigbee2MQTT Dev Console

### ISSUE THREAD

**Issue by mrsmith66** [nurikk/z2m-frontend#2328] opened 2024-12-22 15:18 UTC
### What happened?

When i add a device it shows as unsupported so I go tot the Dev Console but then get an error

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/#/device/0x00124b00199bae11/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:6186)
    at _D (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:5982)
    at a3 (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:44865)
    at J5 (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:39756)
    at Oze (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:35900)
    at AD (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/UEfml2M95LYIuOtPASxxGkas7LbD_qI3gUB-5aUYg-Q/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by mrsmith66** [comment] 2024-12-22 15:19
[initialState.json.zip](https://github.com/user-attachments/files/18222361/initialState.json.zip)
[state.json.zip](https://github.com/user-attachments/files/18222362/state.json.zip)

**Comment by Koenkk** [comment] 2024-12-22 19:58
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-22 19:58 UTC
Labels: bug
