### ISSUE TITLE
Problem with Avatto ZWSM16-1-Zigbee

### ISSUE THREAD

**Issue by andresflower** [nurikk/z2m-frontend#2295] opened 2024-12-13 00:49 UTC
### What happened?

[initialState.json.zip](https://github.com/user-attachments/files/18119124/initialState.json.zip)

After trying to add the device ZWSM16-1-Zigbee wich appears in the compatible devices page, I got an error and the device appears as an unsupported device with no exposes and no nothing.

![image](https://github.com/user-attachments/assets/1d3fe961-bdc3-4ca8-a52c-675cf38fe0b0)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/#/device/0xa4c1386c2b924b25/dev-console
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:6186)
    at _D (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:5982)
    at a3 (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:44865)
    at J5 (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:39756)
    at Oze (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:35900)
    at AD (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/IZMz3y-tb6fZRiIhIIXkh4uEktcF3y6XkZUtwObZFr8/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-13 20:07
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-13 20:07 UTC
Labels: bug
