### ISSUE TITLE
BTH-RM doesnt pair

### ISSUE THREAD

**Issue by ZhuraEN** [nurikk/z2m-frontend#2322] opened 2024-12-21 19:49 UTC
### What happened?

I cant pair Bosch Room thetmostat 2 (battery model)
Trying to do this up ti 20 times/// 
[initialState.json.zip](https://github.com/user-attachments/files/18219752/initialState.json.zip)
![bag](https://github.com/user-attachments/assets/2dbdea58-12a8-452e-b584-0be78b6bdb3f)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.1.110:8081/#/device/0x001e5e090290efe9/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.1.110:8081/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.1.110:8081/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.1.110:8081/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.1.110:8081/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.1.110:8081/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.1.110:8081/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.1.110:8081/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.1.110:8081/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.1.110:8081/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.1.110:8081/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-22 19:39
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-22 19:39 UTC
Labels: bug
