### ISSUE TITLE
Problems adding Frient Air Quality Sensor to zigbee2mqtt in HA 

### ISSUE THREAD

**Issue by bojuelkjeldsen** [nurikk/z2m-frontend#2341] opened 2024-12-27 06:41 UTC
### What happened?

Device not recognised / not supported (Frient AQSZB-110 = Develco AQSZB-110)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/#/device/0x0015bc00360022be/dev-console
**Previous url**: http://192.168.20.70:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.20.70:8123/api/hassio_ingress/VK4tD_Sb-aizqha1Ua2uuN2nwvtugNmirq8QUH8ZOgw/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will not attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-28 13:09
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-28 13:09 UTC
Labels: bug
