### ISSUE TITLE
You found a bug! (opening "dev console" on an uninterviewed device)

### ISSUE THREAD

**Issue by liquidacid** [nurikk/z2m-frontend#2346] opened 2024-12-29 12:05 UTC
### What happened?

I got the error about a bug found. Im trying to add a device but that fails. I was clicking trough the menus when i found this error.

So cant open dev console on a device thats not interviewed correctly.
[initialState.json (1).zip](https://github.com/user-attachments/files/18269516/initialState.json.1.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/#/device/0x70ac08fffe59590b/dev-console
**Previous url**: http://.../45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:6186)
    at _D (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:5982)
    at a3 (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:44865)
    at J5 (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:39756)
    at Oze (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:39682)
    at ap (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:39534)
    at cb (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:35900)
    at AD (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:43:36704)
    at Gn (http://.../api/hassio_ingress/v8yld_7sQQQ84GftED2PMacpmXEwEGMwhy9Y_V4ONEw/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-29 13:51
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-29 13:51 UTC
Labels: bug
