### ISSUE TITLE
Zigbee PIR motion sensor support

### ISSUE THREAD

**Issue by gutekhkey** [nurikk/z2m-frontend#2330] opened 2024-12-22 19:56 UTC
### What happened?

![image](https://github.com/user-attachments/assets/d689459f-bcc5-4d72-8992-d7c325806a61)
z2m: Request 'zigbee2mqtt/bridge/request/device/interview' failed with error: 'interview of '0xa4c1382a3b22c59b' (0xa4c1382a3b22c59b) failed: Error: Interview failed because can not get node descriptor ('0xa4c1382a3b22c59b')')

I tried to pair ONEUNO 808WZ PIR Motion Sensor with CC2531 & Zigbee2MQTT on my HomeAssistant.
[initialState.json.zip](https://github.com/user-attachments/files/18223082/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/#/device/0xa4c1382a3b22c59b/dev-console
**Previous url**: http://11.11.11.50:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:6186)
    at _D (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:5982)
    at a3 (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:44865)
    at J5 (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:39756)
    at Oze (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:39682)
    at ap (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:39534)
    at cb (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:35900)
    at AD (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:43:36704)
    at Gn (http://11.11.11.50:8123/api/hassio_ingress/lZPMC04YLLk2SAVtXaS0DV0BNbtz0LjVg_gmadWulew/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-22 20:00
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-22 20:00 UTC
Labels: bug
