### ISSUE TITLE
Error when entering Dev Console on non-support device

### ISSUE THREAD

**Issue by N30Dym** [nurikk/z2m-frontend#2302] opened 2024-12-14 14:12 UTC
### What happened?

I have recently purchased a new Zigbee device (Avatto Smart Thermostat WT198/ZWT198; IEEE Address: 0xa4c1382c2c3b2c61) that I wanted to add to my Home Assistant. After pairing the device it turned out that it is not supported, yet. I wanted to try to add support using this [guide](https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html). But already when I clicked on the Dev Console Tab the error below appeared.

I was told to report the bug, so here I am.

![grafik](https://github.com/user-attachments/assets/740d4546-97f7-4fbd-83cc-b7f13641703a)

[initialState.json.zip](https://github.com/user-attachments/files/18136173/initialState.json.zip)

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
**Current url**: http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/#/device/0xa4c1382c2c3b2c61/dev-console
**Previous url**: http://XX.XXX.XXX.XXX:8123/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: c.endpoints[r] is undefined



render@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/ConnectedDevicePage-904482a0.js:1:31208
ab@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:6186
_D@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:5982
a3@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:44865
J5@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:39758
Oze@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:39684
ap@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:39534
cb@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:35900
AD@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:36704
Gn@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:41:3283
Wt/<@http://XX.XXX.XXX.XXX:8123/api/hassio_ingress/dj7y76YQLy91gcZzlZGUlrAVhl8eq2DgcftDXWwJurE/assets/index-1213f99f.js:43:34230
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-15 20:00
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2285

**Closed as completed by Koenkk** 2024-12-15 20:00 UTC
Labels: bug
