### ISSUE TITLE
Unable to preload CSS

### ISSUE THREAD

**Issue by NoLan3141** [nurikk/z2m-frontend#2329] opened 2024-12-22 15:47 UTC
### What happened?

![image](https://github.com/user-attachments/assets/2ede66c9-364c-4bd6-a795-eb2e1c1453f3)

zigbee2mqtt does not load correctly even after restarting home assistant
Hardware: raspberry 5 8gb with nmve lexar nm710 
[initialState.json.zip](https://github.com/user-attachments/files/18222460/initialState.json.zip)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeassistant.local:8123/api/hassio_ingress/BNS7-oDQnrqtlARpVCZ8Ehqmhtj23qKdNg8qmATp_Ls/#/
**Previous url**: http://homeassistant.local:8123/45df7312_zigbee2mqtt


**Error type**: Error
**Error message**: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/BNS7-oDQnrqtlARpVCZ8Ehqmhtj23qKdNg8qmATp_Ls/assets/index-e4174e1c.css



Error: Unable to preload CSS for http://homeassistant.local:8123/api/hassio_ingress/BNS7-oDQnrqtlARpVCZ8Ehqmhtj23qKdNg8qmATp_Ls/assets/index-e4174e1c.css
    at HTMLLinkElement.<anonymous> (http://homeassistant.local:8123/api/hassio_ingress/BNS7-oDQnrqtlARpVCZ8Ehqmhtj23qKdNg8qmATp_Ls/assets/index-1213f99f.js:61:9232)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-22 19:59
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2325

**Closed as completed by Koenkk** 2024-12-22 19:59 UTC
Labels: bug
