### ISSUE TITLE
Open DEV Console for unsupported device

### ISSUE THREAD

**Issue by pvillmann** [nurikk/z2m-frontend#2298] opened 2024-12-13 15:32 UTC
### What happened?

Hello, you've found a bug. Congratulations!

[initialState.json.zip](https://github.com/user-attachments/files/18128246/initialState.json.zip)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/#/device/0x0015bc00340024d2/dev-console
**Previous url**: https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:6186)
    at _D (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:5982)
    at a3 (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:44865)
    at J5 (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:39756)
    at Oze (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:39682)
    at ap (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:39534)
    at cb (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:35900)
    at AD (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:43:36704)
    at Gn (https://ezi7jcpmyvudjpizxvxkaeanjguy3md1.ui.nabu.casa/api/hassio_ingress/jED89w-sxeEXPJkHxOcPMF7O66Mn5X6uHwSt0ny3aCM/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-14 12:41
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-14 12:41 UTC
Labels: bug
