### ISSUE TITLE
Error when pairing an IKEA Repeater in a different room: `TypeError:  c.endpoints[r] is undefined`

### ISSUE THREAD

**Issue by Jay2645** [nurikk/z2m-frontend#2287] opened 2024-12-09 22:02 UTC
### What happened?

I'm migrating from ZHA to Zigbee2MQTT. I've paired 3 newer IKEA plugs alongside an older IKEA Repeater they sold alongside their battery-operated blinds.

The first repeater paired successfully, no issues. The second repeater failed during the pairing process, twice. Both times it was the same error and stack trace.

The first repeater was one I paired directly next to my Zigbee stick (a Skyconnect dongle). The repeater that failed is plugged into the USB port on a surge protector in a hard-to-reach area about 2 rooms away from the dongle.

Log has the following errors:

```2024-12-09 13:49:17zh:controller: Interview failed for '0x680ae2fffe6e7c49 with error 'Error: Interview failed because can not get node descriptor ('0x680ae2fffe6e7c49')'
2024-12-09 13:49:17z2m: Failed to interview 'Ikea Repeater 1', device has not successfully been paired
2024-12-09 13:49:17z2m: Request 'zigbee2mqtt/bridge/request/device/remove' failed with error: 'Failed to remove device 'Ikea Repeater 1' (block: false, force: false) (Error: ~x~> [ZDO LEAVE_REQUEST UNICAST to=0x680ae2fffe6e7c49:27481] Failed to send request.)'
2024-12-09 13:51:24zh:controller: Interview failed for '0x680ae2fffe6e7c49 with error 'Error: Interview failed because can not get node descriptor ('0x680ae2fffe6e7c49')'
2024-12-09 13:51:24z2m: Failed to interview 'Ikea Repeater 1', device has not successfully been paired
2024-12-09 13:52:35zh:controller: Interview failed for '0x680ae2fffe6e7c49 with error 'Error: Interview failed because can not get node descriptor ('0x680ae2fffe6e7c49')'
2024-12-09 13:52:35z2m: Failed to interview 'Ikea Repeater 1', device has not successfully been paired
```

(Note that although the log claims this is number 1, it's the second repeater I've tried to pair - the 1 is just the label I put on the side with a Sharpie)

![image](https://github.com/user-attachments/assets/ff16d764-0839-4753-ac34-3ff528252f6f)
![image](https://github.com/user-attachments/assets/12efe80f-0384-4ca5-b245-c0e2f836f5c9)
![image](https://github.com/user-attachments/assets/89b5b38d-8560-46ab-aed1-9632faced96e)

[initialState.json.zip](https://github.com/user-attachments/files/18068554/initialState.json.zip)

EDIT: I was able to pair the repeater successfully when using the same setup as the other repeater that worked - e.g. unplugging it from the surge protector it was plugged in on, moving it close to the Zigbee stick, and then plugging it in to mains power there via a USB charger.

### What browsers are you seeing the problem on?

Firefox

### Relevant stacktrace

```shell
**Current url**: http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/#/device/0x680ae2fffe6e7c49/dev-console
**Previous url**: http://192.168.86.223:8123/45df7312_zigbee2mqtt/ingress


**Error type**: TypeError
**Error message**: c.endpoints[r] is undefined



render@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/ConnectedDevicePage-904482a0.js:1:31208
ab@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:6186
_D@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:5982
a3@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:44865
J5@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:39758
Oze@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:39684
ap@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:39534
cb@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:35900
AD@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:36704
Gn@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:41:3283
Wt/<@http://192.168.86.223:8123/api/hassio_ingress/fPcPIsYfioqMkBMoeMmUiXuHnWb9NDzq0oaWTnz2JUs/assets/index-1213f99f.js:43:34230
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-10 19:21
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2285

**Closed as completed by Koenkk** 2024-12-10 19:21 UTC
Labels: bug
