### ISSUE TITLE
Shown "you've found a bug. Congratulations!" page

### ISSUE THREAD

**Issue by timothygee** [nurikk/z2m-frontend#2338] opened 2024-12-26 02:27 UTC
### What happened?

I am running Zigbee2MQTT in Home Assistant

1. Attempted to pair with IKEA Parasoll
2. Pair failed with 'Error: Interview failed because can not get node descriptor'
3. Clicked on device page
4. Clicked on "how to support"
5. That page told me to go to the "dev console" tab for the device
6. This happened
![image](https://github.com/user-attachments/assets/54fc9246-491f-42dd-8eb8-6de1076c942f)
[initialState.json.zip](https://github.com/user-attachments/files/18248931/initialState.json.zip)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant stacktrace

```shell
**Current url**: http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/#/device/0xd44867fffed492ff/dev-console
**Previous url**: http://192.168.0.100:8123/hassio/ingress/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: Cannot read properties of undefined (reading 'clusters')



TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/ConnectedDevicePage-904482a0.js:1:31232)
    at ab (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:6186)
    at _D (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:5982)
    at a3 (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:44865)
    at J5 (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:39756)
    at Oze (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:39682)
    at ap (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:39534)
    at cb (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:35900)
    at AD (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:43:36704)
    at Gn (http://192.168.0.100:8123/api/hassio_ingress/ll9bjDTXh5WEJ9l3gjn_Eu6rKu4ZXPKwuHav9m_mezM/assets/index-1213f99f.js:41:3283)
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by Koenkk** [comment] 2024-12-28 13:05
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-28 13:05 UTC
Labels: bug
