### ISSUE TITLE
Crash just added device, clicking on 'Dev console' for the device

### ISSUE THREAD

**Issue by roens** [nurikk/z2m-frontend#2333] opened 2024-12-24 02:39 UTC
### What happened?

I was sent here to report this crash by a message from my Z2M install.

I'm adding a device, which is not new to Z2M, as I have two others of the same make/model: A Sylvania RGB bulb, model [73693](https://www.zigbee2mqtt.io/devices/73693.html#sylvania-73693). I have three of these bulbs. One has been out of use, and I'm just now trying to re-add it to Z2M.

These bulbs require being "turned off/on 5 times" to reset. I did this, but because I was doing so by un/screwing the bulb in its socket, I might have got a sixth power cycle in there while Z2M was trying to interview it. So I went clicking around the web UI (as Integration in HAOS).

In the forced-choice "What browsers are you seeing the problem on?", I chose Chrome not because I even have that browser installed, but because I saw this in the Home Assistant Companion macOS app (v2024.12.1, 2024.1041). Because I was prompted by Z2m to submit this "bug" I did not try to reproduce the observed behavior in a regular browser, but would have attempted in Safari (my main browser).

[state.json.zip](https://github.com/user-attachments/files/18235210/state.json.zip)
[initialState.json.zip](https://github.com/user-attachments/files/18235211/initialState.json.zip)
<img width="1690" alt="Screenshot 2024-12-23 at 6 27 40 PM" src="https://github.com/user-attachments/assets/e606f3b0-57c0-4603-8802-effa0efc6fe5" />

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/#/device/0xf0d1b80000024705/dev-console
**Previous url**: 


**Error type**: TypeError
**Error message**: undefined is not an object (evaluating 'c.endpoints[r].clusters')



render@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/ConnectedDevicePage-904482a0.js:1:31231
ab@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:6192
J5@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:39758
Oze@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:39684
ap@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:39537
cb@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:35902
AD@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:36706
Gn@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:41:3284
@http://homeass-yellow.mgmt:8123/api/hassio_ingress/EKHz87cSKpQ_ampofY7nxTCn8AN_A6vsRjOmvmvxB-8/assets/index-1213f99f.js:43:34232
```

### Did you download state.json.zip?

I will attach state.json.zip

**Comment by roens** [comment] 2024-12-24 02:48
# Followup Success

After the above described, and submitting this issue, I again performed a reset of the device (power off/on 5x). After doing this, Z2M succeeded in interviewing the bulb, and it is controllable from both Z2M and HA.

**Comment by Koenkk** [comment] 2024-12-24 20:09
Duplicate of https://github.com/nurikk/zigbee2mqtt-frontend/issues/2293

**Closed as completed by Koenkk** 2024-12-24 20:09 UTC
Labels: bug
